# -*- coding: utf-8 -*-
"""student_predictor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qsna-ftNaWkc2AwRr6tUaCLKl2nHdpxw
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Load dataset
data = pd.read_csv("student_data.csv")

data

data.columns

# Input and output
X = data[['study_hours', 'attendance', 'previous_marks']]
y = data['final_marks']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Prediction example
prediction = model.predict([[6, 80, 70]])
print("Predicted Marks:", prediction)

# Visualization
plt.scatter(data['study_hours'], data['final_marks'])
plt.xlabel("Study Hours")
plt.ylabel("Final Marks")
plt.title("Study Hours vs Marks")
plt.show()

!python student_predictor.py

from sklearn.metrics import r2_score
y_pred = model.predict(X_test)
print("Model Accuracy:", r2_score(y_test, y_pred))